-- Enable pgcrypto so gen_random_uuid() is available on PostgreSQL < 13.
-- On PostgreSQL 13+ gen_random_uuid() is built-in, but enabling the extension is harmless.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- museum_artifact uses a UUID primary key generated by the DB via gen_random_uuid().
-- This is the recommended pattern when:
--   * rows are created by multiple services / shards and serial IDs would collide
--   * you want to expose public IDs without leaking row counts
CREATE TABLE IF NOT EXISTS museum_artifact (
    artifact_id    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    artifact_name  VARCHAR(255) NOT NULL,
    description    TEXT,
    acquired_on    DATE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- You can also let the application supply the UUID:
-- INSERT INTO museum_artifact(artifact_id, artifact_name) VALUES ('...uuid...', 'Mona Lisa');

