package com.testing;

import org.h2.tools.Server;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;

/**
 * $ ls -l /Users/a1353612/pya.*
 * -rw-r--r--  1 py  NA\Domain Users  20480 Jun  9 13:37 /Users/a1353612/pya.mv.db
 * -rw-r--r--  1 py  NA\Domain Users    261 Jun  9 13:37 /Users/a1353612/pya.trace.db
 *
 * http://www.h2database.com/html/features.html#connection_modes
 */
public class H2PostgresTests {

    Server h2MemServer;

    private static final String JDBC_DRIVER = "org.h2.Driver";
    private static final String DATABASE_NAME = "pya";
    private static final String DB_URL = "jdbc:h2:~/" + DATABASE_NAME + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE";

    private static final String USER = "sa";
    private static final String PASS = "";

    H2DbManager h2DbManager = new H2DbManager(DATABASE_NAME, DB_URL, USER, PASS);

    @Before
    public void setup() throws SQLException, ClassNotFoundException {
//        h2MemServer = Server.createPgServer("-tcpPort", "9123", "-tcpAllowOthers").start();
        Class.forName(JDBC_DRIVER);
        String customerSchema = "CREATE TABLE IF NOT EXISTS customer " +
                "(id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, " +
                " first_name VARCHAR(255), " +
                " last_name VARCHAR(255), " +
                " seen_days INTEGER)";
//        applySql(customerSchema);

        var sqls = new LinkedList<String>() {
            {
                add("db/h2/schema.sql");
                add("db/h2/data/data.sql");
            }
        };
        h2DbManager.applySqlScripts(sqls);
    }

    @Test
    public void myTest() throws SQLException {
        try {
            var conn = DriverManager.getConnection(DB_URL, USER, PASS);
            var stmt = conn.createStatement();

            String userDataSql1 = "INSERT INTO customer(first_name, last_name, seen_days) " + "VALUES ('Ya-hard-1', 'PY1', 30)";
            String userDataSql2 = "INSERT INTO customer(first_name, last_name, seen_days) " + "VALUES ('Ya-hard-2', 'PY2', 33)";
            stmt.executeUpdate(userDataSql1);
            System.out.println(userDataSql1);

            stmt.executeUpdate(userDataSql2);
            System.out.println(userDataSql2);

            //
            String sql = "SELECT id, first_name, last_name, seen_days FROM customer";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                int id = rs.getInt("id");
                int age = rs.getInt("seen_days");
                String first = rs.getString("first_name");
                String last = rs.getString("last_name");

                // Display values
                System.out.print("ID: " + id);
                System.out.print(", First: " + first);
                System.out.print(", Last: " + last);
                System.out.println(", Seen Days: " + age);
            }

            stmt.close();
            conn.close();
        } catch (Exception se) {
            se.printStackTrace();
        }
    }

    @After
    public void teardown() {
//        h2MemServer.shutdown();
        h2DbManager.applySql("DROP TABLE customer");
    }
}
